"""1 migrations

Revision ID: 2496c2e54f7b
Revises: a09ba8b72adf
Create Date: 2024-02-19 19:33:26.847860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2496c2e54f7b'
down_revision: Union[str, None] = 'a09ba8b72adf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waybills', 'cargo_description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waybills', 'cargo_weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('waybills', 'cargo_length',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('waybills', 'cargo_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('waybills', 'cargo_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('waybills', 'departure_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waybills', 'destination_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('waybills', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waybills', 'payment_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('waybills', 'destination_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('waybills', 'departure_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('waybills', 'cargo_height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('waybills', 'cargo_width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('waybills', 'cargo_length',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('waybills', 'cargo_weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('waybills', 'cargo_description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
